### ISSUE TITLE
appropriate loader to handle this file type json

### ISSUE THREAD

**Issue by jcc2303** [surmon-china/vue-video-player#10]
Hi @surmon-china 

I learning Vue, I was trying your component but have problems with require json file, 
How can I config to work with your component?

thanks in advance

```sh
ERROR in ./~/vue-video-player/lang/zh-TW.json
Module parse failed: /user/quasar-video/node_modules/vue-video-player/lang/zh-TW.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/user/quasar-video/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/user/quasar-video/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/user/quasar-video/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/user/quasar-video/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/user/quasar-video/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /user/quasar-video/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/user/quasar-video/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
 @ ./~/vue-video-player/languages.js 31:11-39
```

**Comment by surmon-china** [comment]
I test 

```javascript
data () {
      return {
        videoOptions: {
          "source": [
            {
              "type": "video/mp4",
              "src": "http://7xkwa7.media1.z0.glb.cloauddn.com/sample_video_H",
              "label": "原画",
              "res": 1
            },
            {
              "type": "video/mp4",
              "src": "http://221.11.100.42/7xkwa7.masdedia1.z0.glb.clouddn.com/sample_video_M?wsiphost=local",
              "label": "高清",
              "res": 2
            },
            {
              "type": "video/mp4",
              "src": "http://7xkwa7.media1.z0.glb.cloudasdasddn.com/sample_video_L",
              "label": "流畅",
              "res": 3
            }
          ],
          "language": "zh-TW",
          "playbackRates": [
            0.7,
            1,
            1.3,
            1.5,
            1.7
          ],
          "poster": "http://www.freemake.com/blog/wp-content/uploads/2015/06/videojs-logo.jpg",
          "defaultSrcReId": 2,
          "height": 360,
          "autoplay": true
        }
      }
    },
    methods: {
      playerStateChanged(playerCurrentState) {
        console.log(playerCurrentState)
      }
    }
```

It's worked , not error

version: https://github.com/surmon-china/vue-video-player/tree/v2.2.1

**Comment by jcc2303** [comment]
Hi thanks, 

your component work nice,


I haved to install json-loader
and add config webpack
```js
loaders: [
   { test: /\.json$/, loader: 'json' },
   // other loaders 
]
```

I will follow playing with the component.
thanks!
