### ISSUE TITLE
请问在main.js中import VueVideoPlayer from 'vue-video-player' Vue.use(VueVideoPlayer)报这个错误是什么原因？

### ISSUE THREAD

**Issue by jiangzhenggithub** [surmon-china/vue-video-player#116]
e:1 Uncaught SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> xx\node_modules\vue-video-player\index.js:10:23)
    at Object.<anonymous>xx\node_modules\vue-video-player\index.js:23:3)

**Comment by surmon-china** [comment]
近期，组件将会重构升级，届时，将解决这个问题。

**Comment by jiangzhenggithub** [comment]
谢谢

**Comment by surmon-china** [comment]
升级到 v5.0.0

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。
