### ISSUE TITLE
vue-video-player/player.vue Unexpected token (1:0)

### ISSUE THREAD

**Issue by BO-HAI** [surmon-china/vue-video-player#21]
您好，请问这是什么情况，是我的vue-loader有问题吗？我其他.vue都是正常的的。
```
ERROR in ./~/vue-video-player/player.vue
Module parse failed: /Users/bohai/eduProject/hxhz/web/statics/node_modules/vue-video-player/player.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
```

**Comment by surmon-china** [comment]
请提供更详细的信息

**Comment by BO-HAI** [comment]
@surmon-china 
```
ERROR in ./~/vue-video-player/player.vue
Module parse failed: /Users/bohai/eduProject/hxhz/web/statics/node_modules/vue-video-player/player.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)

    at Parser.pp.unexpected (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/bohai/eduProject/hxhz/web/statics/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/bohai/eduProject/hxhz/web/statics/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/bohai/eduProject/hxhz/web/statics/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 @ ./~/vue-video-player/index.js 11:13-36
```

**Comment by BO-HAI** [comment]
@surmon-china  
css编译解决了，但是.vue还是不对，这是我的webpack配置文件：
```
module: {
        loaders: [
            {
                test: /\.vue$/,
                loader: 'vue',
                exclude: /node_modules/
            },
            {
                test: /\.json$/,
                loader: 'json'
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                //loaders: ['es3ify-loader', 'babel', 'eslint-loader']
                // loader: 'es3ify-loader!babel'
                loader: 'babel'
            },
            {
                test: /\.css$/,
                loader: 'style!css!'
            }
        ]
    },
    vue: {
        loaders: {
            js: 'es3ify-loader!babel?{"presets":["es2015"],"plugins": ["transform-object-rest-spread"]}',
            css: 'vue-style!css',
            sass: 'vue-style!css!postcss-loader!sass-loader'
        }
    },
```

**Comment by BO-HAI** [comment]
@surmon-china
问题可以关闭了，是我的问题，我是gulp处理的sass，我没有安装css-loader;   我的vue-loader也是因为忽略掉了node_modules 导致的。
