### ISSUE TITLE
Uncaught ReferenceError: eventEmit is not defined

### ISSUE THREAD

**Issue by lysk** [surmon-china/vue-video-player#47]
使用nuxt 0.10.5 vue-video-player 3.0
直接复制的nuxt-ssr-example下的代码到我项目里，出现
Uncaught ReferenceError: eventEmit is not defined
    at emitPlayerState (eval at <anonymous> (http://127.0.0.1:3000/_nuxt/nuxt.bundle.9df64e8787f5d111d3be.js:1162:1), <anonymous>:72:15)
    at Player.eval (eval at <anonymous> (http://127.0.0.1:3000/_nuxt/nuxt.bundle.9df64e8787f5d111d3be.js:1162:1), <anonymous>:85:13)
    at Player.eval (eval at <anonymous> (http://127.0.0.1:3000/_nuxt/nuxt.bundle.9df64e8787f5d111d3be.js:6:1), <anonymous>:873:14)
    at Array.forEach (native)
    at Player.eval (eval at <anonymous> (http://127.0.0.13000/_nuxt/nuxt.bundle.9df64e8787f5d111d3be.js:6:1), <anonymous>:872:20)
    at bound (eval at <anonymous> (http://127.0.0.1:3000/_nuxt/nuxt.bundle.9df64e8787f5d111d3be.js:13:1), <anonymous>:32:15)
emitPlayerState	@	ssr.js?8c39:72
(anonymous)	        @	ssr.js?8c39:85
(anonymous)	        @	component.js?5748:873
(anonymous)	        @	component.js?5748:872
bound	                @	fn.js?13cb:32

**Comment by surmon-china** [comment]
Thanks for feedback, I will test.

**Comment by surmon-china** [comment]
I fixed this in v3.0.2, just update your dependency and it should work :) !
